image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Mirror to GitHub
        script:
          # Set Git configuration
          - git config --global user.email "you@example.com"
          - git config --global user.name "Your Name"

          # Add GitHub as a remote if not already present
          - git remote add github https://github.com/SayuruRehan/platned-mahara-desktop.git || true

          # Set GitHub remote using secured environment variable for the token
          - git remote set-url github https://SayuruRehan:${GITHUB_TOKEN}@github.com/SayuruRehan/platned-mahara-desktop.git

          # Fetch all history to ensure continuity in the repository
          - git fetch --unshallow || git fetch --all
          
          # Check if DEV branch exists locally, if not, fetch from origin
          - git checkout -b DEV origin/DEV || git checkout DEV

          # Push the DEV branch to GitHub's main branch
          - git push github DEV:main --force

          # Optionally, push tags
          - git push github --tags --force
