image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Mirror Sayuru-Bopitiya branch to GitHub Main
        script:
          # Set Git configuration
          - git config --global user.email "you@example.com"
          - git config --global user.name "Your Name"

          # Add GitHub as a remote if not already present
          - git remote add github https://github.com/SayuruRehan/platned-mahara-desktop.git || true

          # Set GitHub remote using secured environment variable for the token
          - git remote set-url github https://SayuruRehan:${GITHUB_TOKEN}@github.com/SayuruRehan/platned-mahara-desktop.git

          # Fetch all branches from the origin, ensuring unshallow clone
          - git fetch --unshallow || git fetch --all
          - git fetch origin Sayuru-Bopitiya/bitbucketpipelinesyml-created-online-wit-1734607779238 || true
          - git branch -a  # Debug: List all branches to verify if Sayuru-Bopitiya/bitbucketpipelinesyml-created-online-wit-1734607779238 exists

          # Checkout the Sayuru-Bopitiya/bitbucketpipelinesyml-created-online-wit-1734607779238 branch
          - if git show-ref --verify --quiet refs/remotes/origin/Sayuru-Bopitiya/bitbucketpipelinesyml-created-online-wit-1734607779238; then 
              echo "Branch 'Sayuru-Bopitiya/bitbucketpipelinesyml-created-online-wit-1734607779238' found";
              git checkout -b bitbucket-branch origin/Sayuru-Bopitiya/bitbucketpipelinesyml-created-online-wit-1734607779238; 
            else 
              echo "Branch 'Sayuru-Bopitiya/bitbucketpipelinesyml-created-online-wit-1734607779238' not found in remote branches"; 
              exit 1; 
            fi

          # Push the branch to GitHub's main branch
          - git push github HEAD:main --force

          # Optionally, push tags
          - git push github --tags --force
