image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Mirror to GitHub
        script:
          # Set Git configuration
          - git config --global user.email "you@example.com"
          - git config --global user.name "Your Name"

          # Add GitHub as a remote if not already present
          - git remote add github https://github.com/SayuruRehan/platned-mahara-desktop.git || true

          # Set GitHub remote using secured environment variable for the token
          - git remote set-url github https://SayuruRehan:${GITHUB_TOKEN}@github.com/SayuruRehan/platned-mahara-desktop.git

          # Fetch all branches from origin
          - git fetch --all

          # Checkout the DEV branch, fallback to directly checking it out if it exists
          - if git show-ref --verify --quiet refs/heads/DEV; then
              git checkout dev;
            else
              git checkout -b dev origin/dev;
            fi

          # Push the DEV branch to GitHub's main branch
          - git push github dev:main --force

          # Optionally, push tags
          - git push github --tags --force
