image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Mirror DEV to GitHub Main
        script:
          # Set Git configuration
          - git config --global user.email "you@example.com"
          - git config --global user.name "Your Name"

          # Add GitHub as a remote if not already present
          - git remote add github https://github.com/SayuruRehan/platned-mahara-desktop.git || true

          # Set GitHub remote using secured environment variable for the token
          - git remote set-url github https://SayuruRehan:${GITHUB_TOKEN}@github.com/SayuruRehan/platned-mahara-desktop.git

          # Fetch all branches from the origin, ensuring unshallow clone
          - git fetch --unshallow || git fetch --all
          - git fetch origin DEV || true
          - git branch -a  # Debug: List all branches to verify if DEV exists

          # Checkout the DEV branch, fallback to directly checking it out if it exists
          - if git show-ref --verify --quiet Sayuru-Bopitiya/bitbucketpipelinesyml-created-online-wit-1734607779238; then 
              echo "Branch 'DEV' found";
              git checkout -b DEV origin/DEV; 
            elif git show-ref --verify --quiet origin/dev; then 
              git checkout -b dev origin/dev; 
            else 
              echo "Branch 'DEV' or 'dev' not found in remote branches"; 
              exit 1; 
            fi

          # Push the DEV branch to GitHub's main branch
          - git push github HEAD:main --force

          # Optionally, push tags
          - git push github --tags --force
