name: .NET with Unsafe Code - Branch Specific
 
on:
  push:
    branches:
      - DEV
      - Release-PROD
      - Release-TEST
  pull_request:
    branches:
      - DEV
      - Release-PROD
      - Release-TEST
 
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
 
    - name: Restore dependencies
      run: dotnet restore
 
    - name: Build with Unsafe Code Enabled
      run: |
        ACTION_NAME=$([[ ${{ github.event_name }} == 'pull_request' ]] && echo 'PR Build' || echo 'Push Build')
        echo "Running $ACTION_NAME on ${{ github.ref_name }}"
        dotnet build --no-restore -p:AllowUnsafeBlocks=true
 
    - name: Test with Unsafe Code Enabled
      run: |
        ACTION_NAME=$([[ ${{ github.event_name }} == 'pull_request' ]] && echo 'PR Test' || echo 'Push Test')
        echo "Running $ACTION_NAME on ${{ github.ref_name }}"
        dotnet test --no-build --verbosity normal -p:AllowUnsafeBlocks=true
